; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = m5stack-core2-release

[env:m5stack-core2-base]
platform = espressif32 @ 7.0.1
board = m5stack-core2
framework = arduino
upload_speed = 921600
monitor_speed = 115200
board_build.partitions = default_16MB.csv
build_flags =
    -DBOARD_HAS_PSRAM
lib_deps =
; https://github.com/m5stack/M5Unified/tree/master
; https://registry.platformio.org/libraries/m5stack/M5Unified
    m5stack/M5Unified @ 0.2.17
; TODO: find a better GPS/NMEA library?
; https://github.com/mikalhart/TinyGPSPlus
; https://registry.platformio.org/libraries/mikalhart/TinyGPSPlus
    mikalhart/TinyGPSPlus @ 1.1.0

[env:m5stack-core2-debug]
extends = env:m5stack-core2-base
build_type = debug
build_flags =
    ${env:m5stack-core2-base.build_flags}
    -DCORE_DEBUG_LEVEL=5
    -DNSG_LOG_LEVEL=0

[env:m5stack-core2-release]
extends = env:m5stack-core2-base
build_type = release
build_flags =
    ${env:m5stack-core2-base.build_flags}
    -DCORE_DEBUG_LEVEL=0
    -DNSG_LOG_LEVEL=1

; for testing the libs
; $ pio test -e native
[env:native]
platform = native
test_build_src = no
build_flags =
    -std=gnu++17
    -DUNITY_SUPPORT_64